[workspace]
resolver = "2"
members = ["crates/*"]
default-members = ["crates/ledger-desktop"]

[workspace.package]
version = "0.0.1"
edition = "2021"
publish = false
authors = ["Nikita Galaiko <nikita@galaiko.rocks>"]
repository = "https://github.com/ngalaiko/ledger-desktop"
license = "GPL-3.0-only"

[workspace.dependencies]
# errors
thiserror = "2.0"
anyhow = "1.0"

# data types
chrono = "0.4"
fastnum = "0.7"

# serialization
serde = "1.0"
schemars = "1.2"

# async
futures-lite = "2.6"

# gpui
gpui = "0.2.2"
gpui-component = "0.5.0"
gpui-component-assets = "0.5.0"

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
all = "deny"
perf = "deny"
correctness = "deny"
complexity = "deny"
style = "deny"
pedantic = "deny"

[profile.release]
codegen-units = 1 # Compile crates one after another so the compiler can optimize better
lto = true        # Enables link to optimizations
opt-level = "s"   # Optimize for binary size
strip = true      # Remove debug symbols
