[package]
name = "ledger-desktop"
publish.workspace = true
edition.workspace = true
version.workspace = true

[dependencies]
state = { path = "../state" }
ledger = { path = "../ledger" }
ui = { path = "../ui" }

chrono.workspace = true
anyhow.workspace = true
fastnum.workspace = true
serde.workspace = true
schemars.workspace = true
gpui.workspace = true
gpui-component.workspace = true

[lints]
workspace = true
