[package]
name = "ledger-desktop"
publish.workspace = true
edition.workspace = true
version.workspace = true

[dependencies]
state = { path = "../state" }
ledger = { path = "../ledger" }

thiserror.workspace = true
chrono.workspace = true
fastnum.workspace = true
futures-lite.workspace = true
serde.workspace = true
schemars.workspace = true
gpui.workspace = true
gpui-component.workspace = true
gpui-component-assets.workspace = true

[lints]
workspace = true
