[package]
name = "ledger"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
anyhow.workspace = true
thiserror.workspace = true
chrono.workspace = true
fastnum.workspace = true
gpui.workspace = true
serde.workspace = true

async-process = "2.5"
futures-lite = "2.6"
